projects:
  amplifynotes:
    schemaPath: src/graphql/schema.json
    includes:
      - src/graphql/**/*.js
    excludes:
      - amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: src/graphql
        graphQLApiId: cy62f5a5czbybbdmxo4tdtsaru
      endpoints:
        prod: >-
          https://7zhhi6yberhabh224zcp354vtm.appsync-api.us-east-2.amazonaws.com/graphql
